<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="librairie">
  <eClassifiers xsi:type="ecore:EClass" name="Exporter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LibToExpo" eType="#//Librairie"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schema"/>
  <eClassifiers xsi:type="ecore:EClass" name="Calculs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="calculs" eType="#//Données%20import"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contraintes"/>
  <eClassifiers xsi:type="ecore:EClass" name="Algorithmes"/>
  <eClassifiers xsi:type="ecore:EClass" name="Données import">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contraintes" upperBound="-1"
        eType="#//Contraintes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Librairie">
    <eStructuralFeatures xsi:type="ecore:EReference" name="verifications" upperBound="-1"
        eType="#//Données%20import"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CalToLib" upperBound="-1"
        eType="#//Calculs"/>
  </eClassifiers>
</ecore:EPackage>
