/*
 * generated by Xtext 2.32.0
 */
package fr.n7.parser.antlr;

import com.google.inject.Inject;
import fr.n7.parser.antlr.internal.InternalAlgorithme_xtextParser;
import fr.n7.services.Algorithme_xtextGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class Algorithme_xtextParser extends AbstractAntlrParser {

	@Inject
	private Algorithme_xtextGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAlgorithme_xtextParser createParser(XtextTokenStream stream) {
		return new InternalAlgorithme_xtextParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Algorithme";
	}

	public Algorithme_xtextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Algorithme_xtextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
