/**
 * generated by Xtext 2.32.0
 */
package fr.n7.table_xtext.impl;

import fr.n7.table_xtext.ColonneProvient;
import fr.n7.table_xtext.Table;
import fr.n7.table_xtext.Table_xtextPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Colonne Provient</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.table_xtext.impl.ColonneProvientImpl#getTableOrigin <em>Table Origin</em>}</li>
 *   <li>{@link fr.n7.table_xtext.impl.ColonneProvientImpl#getRefColonne <em>Ref Colonne</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ColonneProvientImpl extends ColonnesImpl implements ColonneProvient
{
  /**
   * The cached value of the '{@link #getTableOrigin() <em>Table Origin</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTableOrigin()
   * @generated
   * @ordered
   */
  protected Table tableOrigin;

  /**
   * The default value of the '{@link #getRefColonne() <em>Ref Colonne</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRefColonne()
   * @generated
   * @ordered
   */
  protected static final String REF_COLONNE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRefColonne() <em>Ref Colonne</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRefColonne()
   * @generated
   * @ordered
   */
  protected String refColonne = REF_COLONNE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ColonneProvientImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Table_xtextPackage.Literals.COLONNE_PROVIENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Table getTableOrigin()
  {
    return tableOrigin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTableOrigin(Table newTableOrigin, NotificationChain msgs)
  {
    Table oldTableOrigin = tableOrigin;
    tableOrigin = newTableOrigin;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Table_xtextPackage.COLONNE_PROVIENT__TABLE_ORIGIN, oldTableOrigin, newTableOrigin);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTableOrigin(Table newTableOrigin)
  {
    if (newTableOrigin != tableOrigin)
    {
      NotificationChain msgs = null;
      if (tableOrigin != null)
        msgs = ((InternalEObject)tableOrigin).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Table_xtextPackage.COLONNE_PROVIENT__TABLE_ORIGIN, null, msgs);
      if (newTableOrigin != null)
        msgs = ((InternalEObject)newTableOrigin).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Table_xtextPackage.COLONNE_PROVIENT__TABLE_ORIGIN, null, msgs);
      msgs = basicSetTableOrigin(newTableOrigin, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Table_xtextPackage.COLONNE_PROVIENT__TABLE_ORIGIN, newTableOrigin, newTableOrigin));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRefColonne()
  {
    return refColonne;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRefColonne(String newRefColonne)
  {
    String oldRefColonne = refColonne;
    refColonne = newRefColonne;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Table_xtextPackage.COLONNE_PROVIENT__REF_COLONNE, oldRefColonne, refColonne));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Table_xtextPackage.COLONNE_PROVIENT__TABLE_ORIGIN:
        return basicSetTableOrigin(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Table_xtextPackage.COLONNE_PROVIENT__TABLE_ORIGIN:
        return getTableOrigin();
      case Table_xtextPackage.COLONNE_PROVIENT__REF_COLONNE:
        return getRefColonne();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Table_xtextPackage.COLONNE_PROVIENT__TABLE_ORIGIN:
        setTableOrigin((Table)newValue);
        return;
      case Table_xtextPackage.COLONNE_PROVIENT__REF_COLONNE:
        setRefColonne((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Table_xtextPackage.COLONNE_PROVIENT__TABLE_ORIGIN:
        setTableOrigin((Table)null);
        return;
      case Table_xtextPackage.COLONNE_PROVIENT__REF_COLONNE:
        setRefColonne(REF_COLONNE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Table_xtextPackage.COLONNE_PROVIENT__TABLE_ORIGIN:
        return tableOrigin != null;
      case Table_xtextPackage.COLONNE_PROVIENT__REF_COLONNE:
        return REF_COLONNE_EDEFAULT == null ? refColonne != null : !REF_COLONNE_EDEFAULT.equals(refColonne);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (refColonne: ");
    result.append(refColonne);
    result.append(')');
    return result.toString();
  }

} //ColonneProvientImpl
