/**
 * generated by Xtext 2.32.0
 */
package fr.n7.table_xtext;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bloc Unaire</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.table_xtext.Bloc_Unaire#getOperation <em>Operation</em>}</li>
 * </ul>
 *
 * @see fr.n7.table_xtext.Table_xtextPackage#getBloc_Unaire()
 * @model
 * @generated
 */
public interface Bloc_Unaire extends Bloc
{
  /**
   * Returns the value of the '<em><b>Operation</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.table_xtext.unaire}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' attribute.
   * @see fr.n7.table_xtext.unaire
   * @see #setOperation(unaire)
   * @see fr.n7.table_xtext.Table_xtextPackage#getBloc_Unaire_Operation()
   * @model
   * @generated
   */
  unaire getOperation();

  /**
   * Sets the value of the '{@link fr.n7.table_xtext.Bloc_Unaire#getOperation <em>Operation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation</em>' attribute.
   * @see fr.n7.table_xtext.unaire
   * @see #getOperation()
   * @generated
   */
  void setOperation(unaire value);

} // Bloc_Unaire
