/**
 * generated by Xtext 2.32.0
 */
package fr.n7.table_xtext;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Colonne Derivee</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.table_xtext.ColonneDerivee#getScript <em>Script</em>}</li>
 *   <li>{@link fr.n7.table_xtext.ColonneDerivee#getColonnesEntrees <em>Colonnes Entrees</em>}</li>
 * </ul>
 *
 * @see fr.n7.table_xtext.Table_xtextPackage#getColonneDerivee()
 * @model
 * @generated
 */
public interface ColonneDerivee extends Colonnes
{
  /**
   * Returns the value of the '<em><b>Script</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Script</em>' reference.
   * @see #setScript(Script)
   * @see fr.n7.table_xtext.Table_xtextPackage#getColonneDerivee_Script()
   * @model
   * @generated
   */
  Script getScript();

  /**
   * Sets the value of the '{@link fr.n7.table_xtext.ColonneDerivee#getScript <em>Script</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Script</em>' reference.
   * @see #getScript()
   * @generated
   */
  void setScript(Script value);

  /**
   * Returns the value of the '<em><b>Colonnes Entrees</b></em>' reference list.
   * The list contents are of type {@link fr.n7.table_xtext.Colonne}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Colonnes Entrees</em>' reference list.
   * @see fr.n7.table_xtext.Table_xtextPackage#getColonneDerivee_ColonnesEntrees()
   * @model
   * @generated
   */
  EList<Colonne> getColonnesEntrees();

} // ColonneDerivee
