/**
 * generated by Xtext 2.32.0
 */
package fr.n7.table_xtext;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Colonne</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.n7.table_xtext.Table_xtextPackage#getColonne()
 * @model
 * @generated
 */
public interface Colonne extends Colonnes
{
} // Colonne
