/**
 * generated by Xtext 2.32.0
 */
package fr.n7.table_xtext;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Colonne Provient</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.table_xtext.ColonneProvient#getTableOrigin <em>Table Origin</em>}</li>
 *   <li>{@link fr.n7.table_xtext.ColonneProvient#getRefColonne <em>Ref Colonne</em>}</li>
 * </ul>
 *
 * @see fr.n7.table_xtext.Table_xtextPackage#getColonneProvient()
 * @model
 * @generated
 */
public interface ColonneProvient extends Colonnes
{
  /**
   * Returns the value of the '<em><b>Table Origin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table Origin</em>' containment reference.
   * @see #setTableOrigin(Table)
   * @see fr.n7.table_xtext.Table_xtextPackage#getColonneProvient_TableOrigin()
   * @model containment="true"
   * @generated
   */
  Table getTableOrigin();

  /**
   * Sets the value of the '{@link fr.n7.table_xtext.ColonneProvient#getTableOrigin <em>Table Origin</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table Origin</em>' containment reference.
   * @see #getTableOrigin()
   * @generated
   */
  void setTableOrigin(Table value);

  /**
   * Returns the value of the '<em><b>Ref Colonne</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref Colonne</em>' attribute.
   * @see #setRefColonne(String)
   * @see fr.n7.table_xtext.Table_xtextPackage#getColonneProvient_RefColonne()
   * @model
   * @generated
   */
  String getRefColonne();

  /**
   * Sets the value of the '{@link fr.n7.table_xtext.ColonneProvient#getRefColonne <em>Ref Colonne</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref Colonne</em>' attribute.
   * @see #getRefColonne()
   * @generated
   */
  void setRefColonne(String value);

} // ColonneProvient
