/**
 * generated by Xtext 2.32.0
 */
package fr.n7.table_xtext;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>fonction</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see fr.n7.table_xtext.Table_xtextPackage#getfonction()
 * @model
 * @generated
 */
public enum fonction implements Enumerator
{
  /**
   * The '<em><b>Min</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MIN_VALUE
   * @generated
   * @ordered
   */
  MIN(0, "Min", "min"),

  /**
   * The '<em><b>Max</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MAX_VALUE
   * @generated
   * @ordered
   */
  MAX(1, "Max", "max"),

  /**
   * The '<em><b>Sin</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SIN_VALUE
   * @generated
   * @ordered
   */
  SIN(2, "Sin", "sin"),

  /**
   * The '<em><b>Cos</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COS_VALUE
   * @generated
   * @ordered
   */
  COS(3, "Cos", "cos"),

  /**
   * The '<em><b>Exp</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EXP_VALUE
   * @generated
   * @ordered
   */
  EXP(4, "Exp", "exp"),

  /**
   * The '<em><b>Racine</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RACINE_VALUE
   * @generated
   * @ordered
   */
  RACINE(5, "Racine", "sqrt");

  /**
   * The '<em><b>Min</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MIN
   * @model name="Min" literal="min"
   * @generated
   * @ordered
   */
  public static final int MIN_VALUE = 0;

  /**
   * The '<em><b>Max</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MAX
   * @model name="Max" literal="max"
   * @generated
   * @ordered
   */
  public static final int MAX_VALUE = 1;

  /**
   * The '<em><b>Sin</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SIN
   * @model name="Sin" literal="sin"
   * @generated
   * @ordered
   */
  public static final int SIN_VALUE = 2;

  /**
   * The '<em><b>Cos</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COS
   * @model name="Cos" literal="cos"
   * @generated
   * @ordered
   */
  public static final int COS_VALUE = 3;

  /**
   * The '<em><b>Exp</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EXP
   * @model name="Exp" literal="exp"
   * @generated
   * @ordered
   */
  public static final int EXP_VALUE = 4;

  /**
   * The '<em><b>Racine</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RACINE
   * @model name="Racine" literal="sqrt"
   * @generated
   * @ordered
   */
  public static final int RACINE_VALUE = 5;

  /**
   * An array of all the '<em><b>fonction</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final fonction[] VALUES_ARRAY =
    new fonction[]
    {
      MIN,
      MAX,
      SIN,
      COS,
      EXP,
      RACINE,
    };

  /**
   * A public read-only list of all the '<em><b>fonction</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<fonction> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>fonction</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static fonction get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      fonction result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>fonction</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static fonction getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      fonction result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>fonction</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static fonction get(int value)
  {
    switch (value)
    {
      case MIN_VALUE: return MIN;
      case MAX_VALUE: return MAX;
      case SIN_VALUE: return SIN;
      case COS_VALUE: return COS;
      case EXP_VALUE: return EXP;
      case RACINE_VALUE: return RACINE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private fonction(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //fonction
