/**
 * generated by Xtext 2.32.0
 */
package fr.n7.table_xtext;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicat Colonne</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.table_xtext.PredicatColonne#getColonne <em>Colonne</em>}</li>
 * </ul>
 *
 * @see fr.n7.table_xtext.Table_xtextPackage#getPredicatColonne()
 * @model
 * @generated
 */
public interface PredicatColonne extends Predicat
{
  /**
   * Returns the value of the '<em><b>Colonne</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Colonne</em>' reference.
   * @see #setColonne(Colonnes)
   * @see fr.n7.table_xtext.Table_xtextPackage#getPredicatColonne_Colonne()
   * @model
   * @generated
   */
  Colonnes getColonne();

  /**
   * Sets the value of the '{@link fr.n7.table_xtext.PredicatColonne#getColonne <em>Colonne</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Colonne</em>' reference.
   * @see #getColonne()
   * @generated
   */
  void setColonne(Colonnes value);

} // PredicatColonne
