/**
 * generated by Xtext 2.32.0
 */
package fr.n7.table_xtext;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Script Elements</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.n7.table_xtext.Table_xtextPackage#getScriptElements()
 * @model
 * @generated
 */
public interface ScriptElements extends EObject
{
} // ScriptElements
