/**
 * generated by Xtext 2.32.0
 */
package fr.n7.table_xtext;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.n7.table_xtext.Table_xtextFactory
 * @model kind="package"
 * @generated
 */
public interface Table_xtextPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "table_xtext";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.n7.fr/Table_xtext";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "table_xtext";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Table_xtextPackage eINSTANCE = fr.n7.table_xtext.impl.Table_xtextPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.TableImpl <em>Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.TableImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getTable()
   * @generated
   */
  int TABLE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Colonnes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__COLONNES = 1;

  /**
   * The feature id for the '<em><b>Colonne ID</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__COLONNE_ID = 2;

  /**
   * The feature id for the '<em><b>Scripts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__SCRIPTS = 3;

  /**
   * The number of structural features of the '<em>Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.ColonnesImpl <em>Colonnes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.ColonnesImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getColonnes()
   * @generated
   */
  int COLONNES = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNES__NAME = 0;

  /**
   * The feature id for the '<em><b>Indice</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNES__INDICE = 1;

  /**
   * The feature id for the '<em><b>Element Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNES__ELEMENT_TYPE = 2;

  /**
   * The feature id for the '<em><b>Contraintes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNES__CONTRAINTES = 3;

  /**
   * The feature id for the '<em><b>Nb Lignes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNES__NB_LIGNES = 4;

  /**
   * The number of structural features of the '<em>Colonnes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNES_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.ColonneImpl <em>Colonne</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.ColonneImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getColonne()
   * @generated
   */
  int COLONNE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE__NAME = COLONNES__NAME;

  /**
   * The feature id for the '<em><b>Indice</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE__INDICE = COLONNES__INDICE;

  /**
   * The feature id for the '<em><b>Element Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE__ELEMENT_TYPE = COLONNES__ELEMENT_TYPE;

  /**
   * The feature id for the '<em><b>Contraintes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE__CONTRAINTES = COLONNES__CONTRAINTES;

  /**
   * The feature id for the '<em><b>Nb Lignes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE__NB_LIGNES = COLONNES__NB_LIGNES;

  /**
   * The number of structural features of the '<em>Colonne</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_FEATURE_COUNT = COLONNES_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.ColonneProvientImpl <em>Colonne Provient</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.ColonneProvientImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getColonneProvient()
   * @generated
   */
  int COLONNE_PROVIENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_PROVIENT__NAME = COLONNES__NAME;

  /**
   * The feature id for the '<em><b>Indice</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_PROVIENT__INDICE = COLONNES__INDICE;

  /**
   * The feature id for the '<em><b>Element Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_PROVIENT__ELEMENT_TYPE = COLONNES__ELEMENT_TYPE;

  /**
   * The feature id for the '<em><b>Contraintes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_PROVIENT__CONTRAINTES = COLONNES__CONTRAINTES;

  /**
   * The feature id for the '<em><b>Nb Lignes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_PROVIENT__NB_LIGNES = COLONNES__NB_LIGNES;

  /**
   * The feature id for the '<em><b>Table Origin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_PROVIENT__TABLE_ORIGIN = COLONNES_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ref Colonne</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_PROVIENT__REF_COLONNE = COLONNES_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Colonne Provient</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_PROVIENT_FEATURE_COUNT = COLONNES_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.ColonneDeriveeImpl <em>Colonne Derivee</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.ColonneDeriveeImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getColonneDerivee()
   * @generated
   */
  int COLONNE_DERIVEE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_DERIVEE__NAME = COLONNES__NAME;

  /**
   * The feature id for the '<em><b>Indice</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_DERIVEE__INDICE = COLONNES__INDICE;

  /**
   * The feature id for the '<em><b>Element Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_DERIVEE__ELEMENT_TYPE = COLONNES__ELEMENT_TYPE;

  /**
   * The feature id for the '<em><b>Contraintes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_DERIVEE__CONTRAINTES = COLONNES__CONTRAINTES;

  /**
   * The feature id for the '<em><b>Nb Lignes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_DERIVEE__NB_LIGNES = COLONNES__NB_LIGNES;

  /**
   * The feature id for the '<em><b>Script</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_DERIVEE__SCRIPT = COLONNES_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Colonnes Entrees</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_DERIVEE__COLONNES_ENTREES = COLONNES_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Colonne Derivee</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_DERIVEE_FEATURE_COUNT = COLONNES_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.ContrainteImpl <em>Contrainte</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.ContrainteImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getContrainte()
   * @generated
   */
  int CONTRAINTE = 5;

  /**
   * The number of structural features of the '<em>Contrainte</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRAINTE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.EtImpl <em>Et</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.EtImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getEt()
   * @generated
   */
  int ET = 6;

  /**
   * The feature id for the '<em><b>Variables</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ET__VARIABLES = CONTRAINTE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Et</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ET_FEATURE_COUNT = CONTRAINTE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.OuImpl <em>Ou</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.OuImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getOu()
   * @generated
   */
  int OU = 7;

  /**
   * The feature id for the '<em><b>Variables</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OU__VARIABLES = CONTRAINTE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ou</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OU_FEATURE_COUNT = CONTRAINTE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.PredicatImpl <em>Predicat</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.PredicatImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getPredicat()
   * @generated
   */
  int PREDICAT = 8;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICAT__CONDITION = CONTRAINTE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Predicat</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICAT_FEATURE_COUNT = CONTRAINTE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.PredicatColonneImpl <em>Predicat Colonne</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.PredicatColonneImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getPredicatColonne()
   * @generated
   */
  int PREDICAT_COLONNE = 9;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICAT_COLONNE__CONDITION = PREDICAT__CONDITION;

  /**
   * The feature id for the '<em><b>Colonne</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICAT_COLONNE__COLONNE = PREDICAT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Predicat Colonne</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICAT_COLONNE_FEATURE_COUNT = PREDICAT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.PredicatValeurImpl <em>Predicat Valeur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.PredicatValeurImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getPredicatValeur()
   * @generated
   */
  int PREDICAT_VALEUR = 10;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICAT_VALEUR__CONDITION = PREDICAT__CONDITION;

  /**
   * The feature id for the '<em><b>Valeur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICAT_VALEUR__VALEUR = PREDICAT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Predicat Valeur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICAT_VALEUR_FEATURE_COUNT = PREDICAT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.ScriptImpl <em>Script</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.ScriptImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getScript()
   * @generated
   */
  int SCRIPT = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCRIPT__NAME = 0;

  /**
   * The feature id for the '<em><b>Entrees</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCRIPT__ENTREES = 1;

  /**
   * The feature id for the '<em><b>Script Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCRIPT__SCRIPT_ELEMENTS = 2;

  /**
   * The number of structural features of the '<em>Script</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCRIPT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.ScriptElementsImpl <em>Script Elements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.ScriptElementsImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getScriptElements()
   * @generated
   */
  int SCRIPT_ELEMENTS = 12;

  /**
   * The number of structural features of the '<em>Script Elements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCRIPT_ELEMENTS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.ArgumentImpl <em>Argument</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.ArgumentImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getArgument()
   * @generated
   */
  int ARGUMENT = 13;

  /**
   * The feature id for the '<em><b>Entree</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENT__ENTREE = SCRIPT_ELEMENTS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Argument</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENT_FEATURE_COUNT = SCRIPT_ELEMENTS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.ConstanteImpl <em>Constante</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.ConstanteImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getConstante()
   * @generated
   */
  int CONSTANTE = 14;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE__VAL = SCRIPT_ELEMENTS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Constante</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE_FEATURE_COUNT = SCRIPT_ELEMENTS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.BlocImpl <em>Bloc</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.BlocImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getBloc()
   * @generated
   */
  int BLOC = 15;

  /**
   * The number of structural features of the '<em>Bloc</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOC_FEATURE_COUNT = SCRIPT_ELEMENTS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.Bloc_BinaireImpl <em>Bloc Binaire</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.Bloc_BinaireImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getBloc_Binaire()
   * @generated
   */
  int BLOC_BINAIRE = 16;

  /**
   * The feature id for the '<em><b>Operation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOC_BINAIRE__OPERATION = BLOC_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bloc Binaire</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOC_BINAIRE_FEATURE_COUNT = BLOC_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.Bloc_UnaireImpl <em>Bloc Unaire</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.Bloc_UnaireImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getBloc_Unaire()
   * @generated
   */
  int BLOC_UNAIRE = 17;

  /**
   * The feature id for the '<em><b>Operation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOC_UNAIRE__OPERATION = BLOC_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bloc Unaire</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOC_UNAIRE_FEATURE_COUNT = BLOC_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.impl.Bloc_FonctionImpl <em>Bloc Fonction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.impl.Bloc_FonctionImpl
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getBloc_Fonction()
   * @generated
   */
  int BLOC_FONCTION = 18;

  /**
   * The feature id for the '<em><b>Operation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOC_FONCTION__OPERATION = BLOC_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bloc Fonction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOC_FONCTION_FEATURE_COUNT = BLOC_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.ColonneElementType <em>Colonne Element Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.ColonneElementType
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getColonneElementType()
   * @generated
   */
  int COLONNE_ELEMENT_TYPE = 19;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.Condition <em>Condition</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.Condition
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 20;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.binaire <em>binaire</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.binaire
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getbinaire()
   * @generated
   */
  int BINAIRE = 21;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.unaire <em>unaire</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.unaire
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getunaire()
   * @generated
   */
  int UNAIRE = 22;

  /**
   * The meta object id for the '{@link fr.n7.table_xtext.fonction <em>fonction</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.table_xtext.fonction
   * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getfonction()
   * @generated
   */
  int FONCTION = 23;


  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.Table <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table</em>'.
   * @see fr.n7.table_xtext.Table
   * @generated
   */
  EClass getTable();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.table_xtext.Table#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.table_xtext.Table#getName()
   * @see #getTable()
   * @generated
   */
  EAttribute getTable_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.table_xtext.Table#getColonnes <em>Colonnes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Colonnes</em>'.
   * @see fr.n7.table_xtext.Table#getColonnes()
   * @see #getTable()
   * @generated
   */
  EReference getTable_Colonnes();

  /**
   * Returns the meta object for the reference '{@link fr.n7.table_xtext.Table#getColonneID <em>Colonne ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Colonne ID</em>'.
   * @see fr.n7.table_xtext.Table#getColonneID()
   * @see #getTable()
   * @generated
   */
  EReference getTable_ColonneID();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.table_xtext.Table#getScripts <em>Scripts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Scripts</em>'.
   * @see fr.n7.table_xtext.Table#getScripts()
   * @see #getTable()
   * @generated
   */
  EReference getTable_Scripts();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.Colonnes <em>Colonnes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Colonnes</em>'.
   * @see fr.n7.table_xtext.Colonnes
   * @generated
   */
  EClass getColonnes();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.table_xtext.Colonnes#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.table_xtext.Colonnes#getName()
   * @see #getColonnes()
   * @generated
   */
  EAttribute getColonnes_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.table_xtext.Colonnes#getIndice <em>Indice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Indice</em>'.
   * @see fr.n7.table_xtext.Colonnes#getIndice()
   * @see #getColonnes()
   * @generated
   */
  EAttribute getColonnes_Indice();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.table_xtext.Colonnes#getElementType <em>Element Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Element Type</em>'.
   * @see fr.n7.table_xtext.Colonnes#getElementType()
   * @see #getColonnes()
   * @generated
   */
  EAttribute getColonnes_ElementType();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.table_xtext.Colonnes#getContraintes <em>Contraintes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Contraintes</em>'.
   * @see fr.n7.table_xtext.Colonnes#getContraintes()
   * @see #getColonnes()
   * @generated
   */
  EReference getColonnes_Contraintes();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.table_xtext.Colonnes#getNbLignes <em>Nb Lignes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nb Lignes</em>'.
   * @see fr.n7.table_xtext.Colonnes#getNbLignes()
   * @see #getColonnes()
   * @generated
   */
  EAttribute getColonnes_NbLignes();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.Colonne <em>Colonne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Colonne</em>'.
   * @see fr.n7.table_xtext.Colonne
   * @generated
   */
  EClass getColonne();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.ColonneProvient <em>Colonne Provient</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Colonne Provient</em>'.
   * @see fr.n7.table_xtext.ColonneProvient
   * @generated
   */
  EClass getColonneProvient();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.table_xtext.ColonneProvient#getTableOrigin <em>Table Origin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Table Origin</em>'.
   * @see fr.n7.table_xtext.ColonneProvient#getTableOrigin()
   * @see #getColonneProvient()
   * @generated
   */
  EReference getColonneProvient_TableOrigin();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.table_xtext.ColonneProvient#getRefColonne <em>Ref Colonne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ref Colonne</em>'.
   * @see fr.n7.table_xtext.ColonneProvient#getRefColonne()
   * @see #getColonneProvient()
   * @generated
   */
  EAttribute getColonneProvient_RefColonne();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.ColonneDerivee <em>Colonne Derivee</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Colonne Derivee</em>'.
   * @see fr.n7.table_xtext.ColonneDerivee
   * @generated
   */
  EClass getColonneDerivee();

  /**
   * Returns the meta object for the reference '{@link fr.n7.table_xtext.ColonneDerivee#getScript <em>Script</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Script</em>'.
   * @see fr.n7.table_xtext.ColonneDerivee#getScript()
   * @see #getColonneDerivee()
   * @generated
   */
  EReference getColonneDerivee_Script();

  /**
   * Returns the meta object for the reference list '{@link fr.n7.table_xtext.ColonneDerivee#getColonnesEntrees <em>Colonnes Entrees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Colonnes Entrees</em>'.
   * @see fr.n7.table_xtext.ColonneDerivee#getColonnesEntrees()
   * @see #getColonneDerivee()
   * @generated
   */
  EReference getColonneDerivee_ColonnesEntrees();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.Contrainte <em>Contrainte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contrainte</em>'.
   * @see fr.n7.table_xtext.Contrainte
   * @generated
   */
  EClass getContrainte();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.Et <em>Et</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Et</em>'.
   * @see fr.n7.table_xtext.Et
   * @generated
   */
  EClass getEt();

  /**
   * Returns the meta object for the reference list '{@link fr.n7.table_xtext.Et#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Variables</em>'.
   * @see fr.n7.table_xtext.Et#getVariables()
   * @see #getEt()
   * @generated
   */
  EReference getEt_Variables();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.Ou <em>Ou</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ou</em>'.
   * @see fr.n7.table_xtext.Ou
   * @generated
   */
  EClass getOu();

  /**
   * Returns the meta object for the reference list '{@link fr.n7.table_xtext.Ou#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Variables</em>'.
   * @see fr.n7.table_xtext.Ou#getVariables()
   * @see #getOu()
   * @generated
   */
  EReference getOu_Variables();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.Predicat <em>Predicat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicat</em>'.
   * @see fr.n7.table_xtext.Predicat
   * @generated
   */
  EClass getPredicat();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.table_xtext.Predicat#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see fr.n7.table_xtext.Predicat#getCondition()
   * @see #getPredicat()
   * @generated
   */
  EAttribute getPredicat_Condition();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.PredicatColonne <em>Predicat Colonne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicat Colonne</em>'.
   * @see fr.n7.table_xtext.PredicatColonne
   * @generated
   */
  EClass getPredicatColonne();

  /**
   * Returns the meta object for the reference '{@link fr.n7.table_xtext.PredicatColonne#getColonne <em>Colonne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Colonne</em>'.
   * @see fr.n7.table_xtext.PredicatColonne#getColonne()
   * @see #getPredicatColonne()
   * @generated
   */
  EReference getPredicatColonne_Colonne();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.PredicatValeur <em>Predicat Valeur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicat Valeur</em>'.
   * @see fr.n7.table_xtext.PredicatValeur
   * @generated
   */
  EClass getPredicatValeur();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.table_xtext.PredicatValeur#getValeur <em>Valeur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Valeur</em>'.
   * @see fr.n7.table_xtext.PredicatValeur#getValeur()
   * @see #getPredicatValeur()
   * @generated
   */
  EAttribute getPredicatValeur_Valeur();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.Script <em>Script</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Script</em>'.
   * @see fr.n7.table_xtext.Script
   * @generated
   */
  EClass getScript();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.table_xtext.Script#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.table_xtext.Script#getName()
   * @see #getScript()
   * @generated
   */
  EAttribute getScript_Name();

  /**
   * Returns the meta object for the reference list '{@link fr.n7.table_xtext.Script#getEntrees <em>Entrees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Entrees</em>'.
   * @see fr.n7.table_xtext.Script#getEntrees()
   * @see #getScript()
   * @generated
   */
  EReference getScript_Entrees();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.table_xtext.Script#getScriptElements <em>Script Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Script Elements</em>'.
   * @see fr.n7.table_xtext.Script#getScriptElements()
   * @see #getScript()
   * @generated
   */
  EReference getScript_ScriptElements();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.ScriptElements <em>Script Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Script Elements</em>'.
   * @see fr.n7.table_xtext.ScriptElements
   * @generated
   */
  EClass getScriptElements();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.Argument <em>Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Argument</em>'.
   * @see fr.n7.table_xtext.Argument
   * @generated
   */
  EClass getArgument();

  /**
   * Returns the meta object for the reference '{@link fr.n7.table_xtext.Argument#getEntree <em>Entree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Entree</em>'.
   * @see fr.n7.table_xtext.Argument#getEntree()
   * @see #getArgument()
   * @generated
   */
  EReference getArgument_Entree();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.Constante <em>Constante</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constante</em>'.
   * @see fr.n7.table_xtext.Constante
   * @generated
   */
  EClass getConstante();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.table_xtext.Constante#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see fr.n7.table_xtext.Constante#getVal()
   * @see #getConstante()
   * @generated
   */
  EAttribute getConstante_Val();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.Bloc <em>Bloc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bloc</em>'.
   * @see fr.n7.table_xtext.Bloc
   * @generated
   */
  EClass getBloc();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.Bloc_Binaire <em>Bloc Binaire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bloc Binaire</em>'.
   * @see fr.n7.table_xtext.Bloc_Binaire
   * @generated
   */
  EClass getBloc_Binaire();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.table_xtext.Bloc_Binaire#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation</em>'.
   * @see fr.n7.table_xtext.Bloc_Binaire#getOperation()
   * @see #getBloc_Binaire()
   * @generated
   */
  EAttribute getBloc_Binaire_Operation();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.Bloc_Unaire <em>Bloc Unaire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bloc Unaire</em>'.
   * @see fr.n7.table_xtext.Bloc_Unaire
   * @generated
   */
  EClass getBloc_Unaire();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.table_xtext.Bloc_Unaire#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation</em>'.
   * @see fr.n7.table_xtext.Bloc_Unaire#getOperation()
   * @see #getBloc_Unaire()
   * @generated
   */
  EAttribute getBloc_Unaire_Operation();

  /**
   * Returns the meta object for class '{@link fr.n7.table_xtext.Bloc_Fonction <em>Bloc Fonction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bloc Fonction</em>'.
   * @see fr.n7.table_xtext.Bloc_Fonction
   * @generated
   */
  EClass getBloc_Fonction();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.table_xtext.Bloc_Fonction#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation</em>'.
   * @see fr.n7.table_xtext.Bloc_Fonction#getOperation()
   * @see #getBloc_Fonction()
   * @generated
   */
  EAttribute getBloc_Fonction_Operation();

  /**
   * Returns the meta object for enum '{@link fr.n7.table_xtext.ColonneElementType <em>Colonne Element Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Colonne Element Type</em>'.
   * @see fr.n7.table_xtext.ColonneElementType
   * @generated
   */
  EEnum getColonneElementType();

  /**
   * Returns the meta object for enum '{@link fr.n7.table_xtext.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Condition</em>'.
   * @see fr.n7.table_xtext.Condition
   * @generated
   */
  EEnum getCondition();

  /**
   * Returns the meta object for enum '{@link fr.n7.table_xtext.binaire <em>binaire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>binaire</em>'.
   * @see fr.n7.table_xtext.binaire
   * @generated
   */
  EEnum getbinaire();

  /**
   * Returns the meta object for enum '{@link fr.n7.table_xtext.unaire <em>unaire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>unaire</em>'.
   * @see fr.n7.table_xtext.unaire
   * @generated
   */
  EEnum getunaire();

  /**
   * Returns the meta object for enum '{@link fr.n7.table_xtext.fonction <em>fonction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>fonction</em>'.
   * @see fr.n7.table_xtext.fonction
   * @generated
   */
  EEnum getfonction();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  Table_xtextFactory getTable_xtextFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.TableImpl <em>Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.TableImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getTable()
     * @generated
     */
    EClass TABLE = eINSTANCE.getTable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE__NAME = eINSTANCE.getTable_Name();

    /**
     * The meta object literal for the '<em><b>Colonnes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE__COLONNES = eINSTANCE.getTable_Colonnes();

    /**
     * The meta object literal for the '<em><b>Colonne ID</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE__COLONNE_ID = eINSTANCE.getTable_ColonneID();

    /**
     * The meta object literal for the '<em><b>Scripts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE__SCRIPTS = eINSTANCE.getTable_Scripts();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.ColonnesImpl <em>Colonnes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.ColonnesImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getColonnes()
     * @generated
     */
    EClass COLONNES = eINSTANCE.getColonnes();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLONNES__NAME = eINSTANCE.getColonnes_Name();

    /**
     * The meta object literal for the '<em><b>Indice</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLONNES__INDICE = eINSTANCE.getColonnes_Indice();

    /**
     * The meta object literal for the '<em><b>Element Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLONNES__ELEMENT_TYPE = eINSTANCE.getColonnes_ElementType();

    /**
     * The meta object literal for the '<em><b>Contraintes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLONNES__CONTRAINTES = eINSTANCE.getColonnes_Contraintes();

    /**
     * The meta object literal for the '<em><b>Nb Lignes</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLONNES__NB_LIGNES = eINSTANCE.getColonnes_NbLignes();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.ColonneImpl <em>Colonne</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.ColonneImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getColonne()
     * @generated
     */
    EClass COLONNE = eINSTANCE.getColonne();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.ColonneProvientImpl <em>Colonne Provient</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.ColonneProvientImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getColonneProvient()
     * @generated
     */
    EClass COLONNE_PROVIENT = eINSTANCE.getColonneProvient();

    /**
     * The meta object literal for the '<em><b>Table Origin</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLONNE_PROVIENT__TABLE_ORIGIN = eINSTANCE.getColonneProvient_TableOrigin();

    /**
     * The meta object literal for the '<em><b>Ref Colonne</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLONNE_PROVIENT__REF_COLONNE = eINSTANCE.getColonneProvient_RefColonne();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.ColonneDeriveeImpl <em>Colonne Derivee</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.ColonneDeriveeImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getColonneDerivee()
     * @generated
     */
    EClass COLONNE_DERIVEE = eINSTANCE.getColonneDerivee();

    /**
     * The meta object literal for the '<em><b>Script</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLONNE_DERIVEE__SCRIPT = eINSTANCE.getColonneDerivee_Script();

    /**
     * The meta object literal for the '<em><b>Colonnes Entrees</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLONNE_DERIVEE__COLONNES_ENTREES = eINSTANCE.getColonneDerivee_ColonnesEntrees();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.ContrainteImpl <em>Contrainte</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.ContrainteImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getContrainte()
     * @generated
     */
    EClass CONTRAINTE = eINSTANCE.getContrainte();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.EtImpl <em>Et</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.EtImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getEt()
     * @generated
     */
    EClass ET = eINSTANCE.getEt();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ET__VARIABLES = eINSTANCE.getEt_Variables();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.OuImpl <em>Ou</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.OuImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getOu()
     * @generated
     */
    EClass OU = eINSTANCE.getOu();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OU__VARIABLES = eINSTANCE.getOu_Variables();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.PredicatImpl <em>Predicat</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.PredicatImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getPredicat()
     * @generated
     */
    EClass PREDICAT = eINSTANCE.getPredicat();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICAT__CONDITION = eINSTANCE.getPredicat_Condition();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.PredicatColonneImpl <em>Predicat Colonne</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.PredicatColonneImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getPredicatColonne()
     * @generated
     */
    EClass PREDICAT_COLONNE = eINSTANCE.getPredicatColonne();

    /**
     * The meta object literal for the '<em><b>Colonne</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICAT_COLONNE__COLONNE = eINSTANCE.getPredicatColonne_Colonne();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.PredicatValeurImpl <em>Predicat Valeur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.PredicatValeurImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getPredicatValeur()
     * @generated
     */
    EClass PREDICAT_VALEUR = eINSTANCE.getPredicatValeur();

    /**
     * The meta object literal for the '<em><b>Valeur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICAT_VALEUR__VALEUR = eINSTANCE.getPredicatValeur_Valeur();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.ScriptImpl <em>Script</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.ScriptImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getScript()
     * @generated
     */
    EClass SCRIPT = eINSTANCE.getScript();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCRIPT__NAME = eINSTANCE.getScript_Name();

    /**
     * The meta object literal for the '<em><b>Entrees</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCRIPT__ENTREES = eINSTANCE.getScript_Entrees();

    /**
     * The meta object literal for the '<em><b>Script Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCRIPT__SCRIPT_ELEMENTS = eINSTANCE.getScript_ScriptElements();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.ScriptElementsImpl <em>Script Elements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.ScriptElementsImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getScriptElements()
     * @generated
     */
    EClass SCRIPT_ELEMENTS = eINSTANCE.getScriptElements();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.ArgumentImpl <em>Argument</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.ArgumentImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getArgument()
     * @generated
     */
    EClass ARGUMENT = eINSTANCE.getArgument();

    /**
     * The meta object literal for the '<em><b>Entree</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARGUMENT__ENTREE = eINSTANCE.getArgument_Entree();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.ConstanteImpl <em>Constante</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.ConstanteImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getConstante()
     * @generated
     */
    EClass CONSTANTE = eINSTANCE.getConstante();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANTE__VAL = eINSTANCE.getConstante_Val();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.BlocImpl <em>Bloc</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.BlocImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getBloc()
     * @generated
     */
    EClass BLOC = eINSTANCE.getBloc();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.Bloc_BinaireImpl <em>Bloc Binaire</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.Bloc_BinaireImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getBloc_Binaire()
     * @generated
     */
    EClass BLOC_BINAIRE = eINSTANCE.getBloc_Binaire();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLOC_BINAIRE__OPERATION = eINSTANCE.getBloc_Binaire_Operation();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.Bloc_UnaireImpl <em>Bloc Unaire</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.Bloc_UnaireImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getBloc_Unaire()
     * @generated
     */
    EClass BLOC_UNAIRE = eINSTANCE.getBloc_Unaire();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLOC_UNAIRE__OPERATION = eINSTANCE.getBloc_Unaire_Operation();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.impl.Bloc_FonctionImpl <em>Bloc Fonction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.impl.Bloc_FonctionImpl
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getBloc_Fonction()
     * @generated
     */
    EClass BLOC_FONCTION = eINSTANCE.getBloc_Fonction();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLOC_FONCTION__OPERATION = eINSTANCE.getBloc_Fonction_Operation();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.ColonneElementType <em>Colonne Element Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.ColonneElementType
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getColonneElementType()
     * @generated
     */
    EEnum COLONNE_ELEMENT_TYPE = eINSTANCE.getColonneElementType();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.Condition <em>Condition</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.Condition
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getCondition()
     * @generated
     */
    EEnum CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.binaire <em>binaire</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.binaire
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getbinaire()
     * @generated
     */
    EEnum BINAIRE = eINSTANCE.getbinaire();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.unaire <em>unaire</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.unaire
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getunaire()
     * @generated
     */
    EEnum UNAIRE = eINSTANCE.getunaire();

    /**
     * The meta object literal for the '{@link fr.n7.table_xtext.fonction <em>fonction</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.table_xtext.fonction
     * @see fr.n7.table_xtext.impl.Table_xtextPackageImpl#getfonction()
     * @generated
     */
    EEnum FONCTION = eINSTANCE.getfonction();

  }

} //Table_xtextPackage
