/**
 * generated by Xtext 2.32.0
 */
package fr.n7.table_xtext;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see fr.n7.table_xtext.Table_xtextPackage
 * @generated
 */
public interface Table_xtextFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Table_xtextFactory eINSTANCE = fr.n7.table_xtext.impl.Table_xtextFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Table</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table</em>'.
   * @generated
   */
  Table createTable();

  /**
   * Returns a new object of class '<em>Colonnes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Colonnes</em>'.
   * @generated
   */
  Colonnes createColonnes();

  /**
   * Returns a new object of class '<em>Colonne</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Colonne</em>'.
   * @generated
   */
  Colonne createColonne();

  /**
   * Returns a new object of class '<em>Colonne Provient</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Colonne Provient</em>'.
   * @generated
   */
  ColonneProvient createColonneProvient();

  /**
   * Returns a new object of class '<em>Colonne Derivee</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Colonne Derivee</em>'.
   * @generated
   */
  ColonneDerivee createColonneDerivee();

  /**
   * Returns a new object of class '<em>Contrainte</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contrainte</em>'.
   * @generated
   */
  Contrainte createContrainte();

  /**
   * Returns a new object of class '<em>Et</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Et</em>'.
   * @generated
   */
  Et createEt();

  /**
   * Returns a new object of class '<em>Ou</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ou</em>'.
   * @generated
   */
  Ou createOu();

  /**
   * Returns a new object of class '<em>Predicat</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Predicat</em>'.
   * @generated
   */
  Predicat createPredicat();

  /**
   * Returns a new object of class '<em>Predicat Colonne</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Predicat Colonne</em>'.
   * @generated
   */
  PredicatColonne createPredicatColonne();

  /**
   * Returns a new object of class '<em>Predicat Valeur</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Predicat Valeur</em>'.
   * @generated
   */
  PredicatValeur createPredicatValeur();

  /**
   * Returns a new object of class '<em>Script</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Script</em>'.
   * @generated
   */
  Script createScript();

  /**
   * Returns a new object of class '<em>Script Elements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Script Elements</em>'.
   * @generated
   */
  ScriptElements createScriptElements();

  /**
   * Returns a new object of class '<em>Argument</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Argument</em>'.
   * @generated
   */
  Argument createArgument();

  /**
   * Returns a new object of class '<em>Constante</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constante</em>'.
   * @generated
   */
  Constante createConstante();

  /**
   * Returns a new object of class '<em>Bloc</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bloc</em>'.
   * @generated
   */
  Bloc createBloc();

  /**
   * Returns a new object of class '<em>Bloc Binaire</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bloc Binaire</em>'.
   * @generated
   */
  Bloc_Binaire createBloc_Binaire();

  /**
   * Returns a new object of class '<em>Bloc Unaire</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bloc Unaire</em>'.
   * @generated
   */
  Bloc_Unaire createBloc_Unaire();

  /**
   * Returns a new object of class '<em>Bloc Fonction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bloc Fonction</em>'.
   * @generated
   */
  Bloc_Fonction createBloc_Fonction();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  Table_xtextPackage getTable_xtextPackage();

} //Table_xtextFactory
