/*
 * generated by Xtext 2.32.0
 */
package fr.n7.ui;

import com.google.inject.Injector;
import fr.n7.algorithme_xtext.ui.internal.Algorithme_xtextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Algorithme_xtextExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Algorithme_xtextActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Algorithme_xtextActivator activator = Algorithme_xtextActivator.getInstance();
		return activator != null ? activator.getInjector(Algorithme_xtextActivator.FR_N7_ALGORITHME_XTEXT) : null;
	}

}
