/*
 * generated by Xtext 2.32.0
 */
package fr.n7.parser.antlr;

import com.google.inject.Inject;
import fr.n7.parser.antlr.internal.InternalTable_xtextParser;
import fr.n7.services.Table_xtextGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class Table_xtextParser extends AbstractAntlrParser {

	@Inject
	private Table_xtextGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTable_xtextParser createParser(XtextTokenStream stream) {
		return new InternalTable_xtextParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Table";
	}

	public Table_xtextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Table_xtextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
