<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="script" nsURI="http://script" nsPrefix="script">
  <eClassifiers xsi:type="ecore:EClass" name="Script">
    <eStructuralFeatures xsi:type="ecore:EReference" name="StoSE" upperBound="-1"
        eType="#//ScriptElements" containment="true" eOpposite="#//ScriptElements/SEtos"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScriptElements" abstract="true" eSuperTypes="#//Script">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SEtos" eType="#//Script"
        eOpposite="#//Script/StoSE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortEntree">
    <eStructuralFeatures xsi:type="ecore:EReference" name="PEtoBU" eType="#//Bloc_Unaire"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PEtoBB" eType="#//Bloc_Binaire"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PEtoBF" eType="#//Bloc_Fonction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortSortie">
    <eStructuralFeatures xsi:type="ecore:EReference" name="PStoBU" eType="#//Bloc_Unaire"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PStoBB" eType="#//Bloc_Binaire"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PStoBF" eType="#//Bloc_Fonction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entree" eSuperTypes="#//PortEntree">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arg" upperBound="-1" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sortie" eSuperTypes="#//PortSortie">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="res" upperBound="-1" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bloc_Binaire">
    <eStructuralFeatures xsi:type="ecore:EReference" name="BBtoS" upperBound="-1"
        eType="#//ScriptElements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bloc_Unaire">
    <eStructuralFeatures xsi:type="ecore:EReference" name="BUtoS" upperBound="-1"
        eType="#//ScriptElements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bloc_Fonction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="BFtoS" upperBound="-1"
        eType="#//ScriptElements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Addition" eSuperTypes="#//Bloc_Binaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplication" eSuperTypes="#//Bloc_Binaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Division" eSuperTypes="#//Bloc_Binaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Min" eSuperTypes="#//Bloc_Binaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Max" eSuperTypes="#//Bloc_Binaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Oppose" eSuperTypes="#//Bloc_Unaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inverse" eSuperTypes="#//Bloc_Unaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sin" eSuperTypes="#//Bloc_Fonction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cos" eSuperTypes="#//Bloc_Fonction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Racine" eSuperTypes="#//Bloc_Fonction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expo" eSuperTypes="#//Bloc_Fonction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constante">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CtoS" upperBound="-1" eType="#//Script"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type" instanceTypeName="Var">
    <eLiterals name="INT"/>
    <eLiterals name="FLOAT" value="1"/>
    <eLiterals name="BOOL" value="2"/>
    <eLiterals name="STRING" value="3"/>
  </eClassifiers>
</ecore:EPackage>
