<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Script">
  <eClassifiers xsi:type="ecore:EClass" name="Script"/>
  <eClassifiers xsi:type="ecore:EClass" name="E/S">
    <eStructuralFeatures xsi:type="ecore:EReference" name="E/StoS" eType="#//Script"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entree" eSuperTypes="#//E%2FS"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sortie" eSuperTypes="#//E%2FS"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bloc_Binaire">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BBtoS" upperBound="-1"
        eType="#//Script"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bloc_Unaire">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BUtoS" upperBound="-1"
        eType="#//Script"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bloc_Fonction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BFtoS" upperBound="-1"
        eType="#//Script"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Addition" eSuperTypes="#//Bloc_Binaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplication" eSuperTypes="#//Bloc_Binaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Division" eSuperTypes="#//Bloc_Binaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Min" eSuperTypes="#//Bloc_Binaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Max" eSuperTypes="#//Bloc_Binaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Oppose" eSuperTypes="#//Bloc_Unaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inverse" eSuperTypes="#//Bloc_Unaire"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sin" eSuperTypes="#//Bloc_Fonction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cos" eSuperTypes="#//Bloc_Fonction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Racine" eSuperTypes="#//Bloc_Fonction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expo" eSuperTypes="#//Bloc_Fonction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constante">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CtoS" upperBound="-1" eType="#//Script"/>
  </eClassifiers>
</ecore:EPackage>
