<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Algorithme" nsURI="http://Algorithme" nsPrefix="Algorithme">
  <eClassifiers xsi:type="ecore:EClass" name="Algorithme"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ressources">
    <eStructuralFeatures xsi:type="ecore:EReference" name="RtoA" upperBound="-1" eType="#//Algorithme"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RtoE_S" upperBound="-1"
        eType="#//E_S"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Programme" eSuperTypes="#//Ressources"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fichier" eSuperTypes="#//Ressources"/>
  <eClassifiers xsi:type="ecore:EClass" name="Guidance" eSuperTypes="#//Algorithme">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Algorithme"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="texte" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="E_S">
    <eStructuralFeatures xsi:type="ecore:EReference" name="E_StoA" upperBound="-1"
        eType="#//Algorithme"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entrée" eSuperTypes="#//E_S">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paramètre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sortie" eSuperTypes="#//E_S"/>
</ecore:EPackage>
