/*
 * generated by Xtext 2.32.0
 */
package fr.n7.ui;

import com.google.inject.Injector;
import fr.n7.table_xtext.ui.internal.Table_xtextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Table_xtextExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Table_xtextActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Table_xtextActivator activator = Table_xtextActivator.getInstance();
		return activator != null ? activator.getInjector(Table_xtextActivator.FR_N7_TABLE_XTEXT) : null;
	}

}
