/**
 * generated by Xtext 2.32.0
 */
package fr.n7.algorithme_xtext.impl;

import fr.n7.algorithme_xtext.AlgorithmeElements;
import fr.n7.algorithme_xtext.Algorithme_xtextPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Algorithme Elements</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AlgorithmeElementsImpl extends MinimalEObjectImpl.Container implements AlgorithmeElements
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AlgorithmeElementsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Algorithme_xtextPackage.Literals.ALGORITHME_ELEMENTS;
  }

} //AlgorithmeElementsImpl
