/**
 * generated by Xtext 2.32.0
 */
package fr.n7.algorithme_xtext;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.n7.algorithme_xtext.Algorithme_xtextFactory
 * @model kind="package"
 * @generated
 */
public interface Algorithme_xtextPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "algorithme_xtext";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.n7.fr/Algorithme_xtext";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "algorithme_xtext";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Algorithme_xtextPackage eINSTANCE = fr.n7.algorithme_xtext.impl.Algorithme_xtextPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.n7.algorithme_xtext.impl.AlgorithmeImpl <em>Algorithme</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.algorithme_xtext.impl.AlgorithmeImpl
   * @see fr.n7.algorithme_xtext.impl.Algorithme_xtextPackageImpl#getAlgorithme()
   * @generated
   */
  int ALGORITHME = 0;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME__NOM = 0;

  /**
   * The feature id for the '<em><b>Algorithme Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME__ALGORITHME_ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Algorithme</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.n7.algorithme_xtext.impl.AlgorithmeElementsImpl <em>Algorithme Elements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.algorithme_xtext.impl.AlgorithmeElementsImpl
   * @see fr.n7.algorithme_xtext.impl.Algorithme_xtextPackageImpl#getAlgorithmeElements()
   * @generated
   */
  int ALGORITHME_ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Algorithme Elements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME_ELEMENTS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.n7.algorithme_xtext.impl.RessourcesImpl <em>Ressources</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.algorithme_xtext.impl.RessourcesImpl
   * @see fr.n7.algorithme_xtext.impl.Algorithme_xtextPackageImpl#getRessources()
   * @generated
   */
  int RESSOURCES = 2;

  /**
   * The feature id for the '<em><b>Chemin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESSOURCES__CHEMIN = ALGORITHME_ELEMENTS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Script</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESSOURCES__SCRIPT = ALGORITHME_ELEMENTS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Ressources</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESSOURCES_FEATURE_COUNT = ALGORITHME_ELEMENTS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.n7.algorithme_xtext.impl.DocumentationImpl <em>Documentation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.algorithme_xtext.impl.DocumentationImpl
   * @see fr.n7.algorithme_xtext.impl.Algorithme_xtextPackageImpl#getDocumentation()
   * @generated
   */
  int DOCUMENTATION = 3;

  /**
   * The feature id for the '<em><b>Texte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENTATION__TEXTE = ALGORITHME_ELEMENTS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Documentation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENTATION_FEATURE_COUNT = ALGORITHME_ELEMENTS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.algorithme_xtext.impl.EntreeImpl <em>Entree</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.algorithme_xtext.impl.EntreeImpl
   * @see fr.n7.algorithme_xtext.impl.Algorithme_xtextPackageImpl#getEntree()
   * @generated
   */
  int ENTREE = 4;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTREE__NOM = 0;

  /**
   * The feature id for the '<em><b>Valeur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTREE__VALEUR = 1;

  /**
   * The number of structural features of the '<em>Entree</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTREE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.n7.algorithme_xtext.impl.SortieImpl <em>Sortie</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.algorithme_xtext.impl.SortieImpl
   * @see fr.n7.algorithme_xtext.impl.Algorithme_xtextPackageImpl#getSortie()
   * @generated
   */
  int SORTIE = 5;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SORTIE__NOM = 0;

  /**
   * The feature id for the '<em><b>Valeur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SORTIE__VALEUR = 1;

  /**
   * The number of structural features of the '<em>Sortie</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SORTIE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link fr.n7.algorithme_xtext.Algorithme <em>Algorithme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Algorithme</em>'.
   * @see fr.n7.algorithme_xtext.Algorithme
   * @generated
   */
  EClass getAlgorithme();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.algorithme_xtext.Algorithme#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see fr.n7.algorithme_xtext.Algorithme#getNom()
   * @see #getAlgorithme()
   * @generated
   */
  EAttribute getAlgorithme_Nom();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.algorithme_xtext.Algorithme#getAlgorithmeElements <em>Algorithme Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Algorithme Elements</em>'.
   * @see fr.n7.algorithme_xtext.Algorithme#getAlgorithmeElements()
   * @see #getAlgorithme()
   * @generated
   */
  EReference getAlgorithme_AlgorithmeElements();

  /**
   * Returns the meta object for class '{@link fr.n7.algorithme_xtext.AlgorithmeElements <em>Algorithme Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Algorithme Elements</em>'.
   * @see fr.n7.algorithme_xtext.AlgorithmeElements
   * @generated
   */
  EClass getAlgorithmeElements();

  /**
   * Returns the meta object for class '{@link fr.n7.algorithme_xtext.Ressources <em>Ressources</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ressources</em>'.
   * @see fr.n7.algorithme_xtext.Ressources
   * @generated
   */
  EClass getRessources();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.algorithme_xtext.Ressources#getChemin <em>Chemin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Chemin</em>'.
   * @see fr.n7.algorithme_xtext.Ressources#getChemin()
   * @see #getRessources()
   * @generated
   */
  EAttribute getRessources_Chemin();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.algorithme_xtext.Ressources#getScript <em>Script</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Script</em>'.
   * @see fr.n7.algorithme_xtext.Ressources#getScript()
   * @see #getRessources()
   * @generated
   */
  EAttribute getRessources_Script();

  /**
   * Returns the meta object for class '{@link fr.n7.algorithme_xtext.Documentation <em>Documentation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Documentation</em>'.
   * @see fr.n7.algorithme_xtext.Documentation
   * @generated
   */
  EClass getDocumentation();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.algorithme_xtext.Documentation#getTexte <em>Texte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texte</em>'.
   * @see fr.n7.algorithme_xtext.Documentation#getTexte()
   * @see #getDocumentation()
   * @generated
   */
  EAttribute getDocumentation_Texte();

  /**
   * Returns the meta object for class '{@link fr.n7.algorithme_xtext.Entree <em>Entree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entree</em>'.
   * @see fr.n7.algorithme_xtext.Entree
   * @generated
   */
  EClass getEntree();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.algorithme_xtext.Entree#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see fr.n7.algorithme_xtext.Entree#getNom()
   * @see #getEntree()
   * @generated
   */
  EAttribute getEntree_Nom();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.algorithme_xtext.Entree#getValeur <em>Valeur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Valeur</em>'.
   * @see fr.n7.algorithme_xtext.Entree#getValeur()
   * @see #getEntree()
   * @generated
   */
  EAttribute getEntree_Valeur();

  /**
   * Returns the meta object for class '{@link fr.n7.algorithme_xtext.Sortie <em>Sortie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sortie</em>'.
   * @see fr.n7.algorithme_xtext.Sortie
   * @generated
   */
  EClass getSortie();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.algorithme_xtext.Sortie#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see fr.n7.algorithme_xtext.Sortie#getNom()
   * @see #getSortie()
   * @generated
   */
  EAttribute getSortie_Nom();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.algorithme_xtext.Sortie#getValeur <em>Valeur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Valeur</em>'.
   * @see fr.n7.algorithme_xtext.Sortie#getValeur()
   * @see #getSortie()
   * @generated
   */
  EAttribute getSortie_Valeur();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  Algorithme_xtextFactory getAlgorithme_xtextFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.n7.algorithme_xtext.impl.AlgorithmeImpl <em>Algorithme</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.algorithme_xtext.impl.AlgorithmeImpl
     * @see fr.n7.algorithme_xtext.impl.Algorithme_xtextPackageImpl#getAlgorithme()
     * @generated
     */
    EClass ALGORITHME = eINSTANCE.getAlgorithme();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHME__NOM = eINSTANCE.getAlgorithme_Nom();

    /**
     * The meta object literal for the '<em><b>Algorithme Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALGORITHME__ALGORITHME_ELEMENTS = eINSTANCE.getAlgorithme_AlgorithmeElements();

    /**
     * The meta object literal for the '{@link fr.n7.algorithme_xtext.impl.AlgorithmeElementsImpl <em>Algorithme Elements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.algorithme_xtext.impl.AlgorithmeElementsImpl
     * @see fr.n7.algorithme_xtext.impl.Algorithme_xtextPackageImpl#getAlgorithmeElements()
     * @generated
     */
    EClass ALGORITHME_ELEMENTS = eINSTANCE.getAlgorithmeElements();

    /**
     * The meta object literal for the '{@link fr.n7.algorithme_xtext.impl.RessourcesImpl <em>Ressources</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.algorithme_xtext.impl.RessourcesImpl
     * @see fr.n7.algorithme_xtext.impl.Algorithme_xtextPackageImpl#getRessources()
     * @generated
     */
    EClass RESSOURCES = eINSTANCE.getRessources();

    /**
     * The meta object literal for the '<em><b>Chemin</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESSOURCES__CHEMIN = eINSTANCE.getRessources_Chemin();

    /**
     * The meta object literal for the '<em><b>Script</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESSOURCES__SCRIPT = eINSTANCE.getRessources_Script();

    /**
     * The meta object literal for the '{@link fr.n7.algorithme_xtext.impl.DocumentationImpl <em>Documentation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.algorithme_xtext.impl.DocumentationImpl
     * @see fr.n7.algorithme_xtext.impl.Algorithme_xtextPackageImpl#getDocumentation()
     * @generated
     */
    EClass DOCUMENTATION = eINSTANCE.getDocumentation();

    /**
     * The meta object literal for the '<em><b>Texte</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOCUMENTATION__TEXTE = eINSTANCE.getDocumentation_Texte();

    /**
     * The meta object literal for the '{@link fr.n7.algorithme_xtext.impl.EntreeImpl <em>Entree</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.algorithme_xtext.impl.EntreeImpl
     * @see fr.n7.algorithme_xtext.impl.Algorithme_xtextPackageImpl#getEntree()
     * @generated
     */
    EClass ENTREE = eINSTANCE.getEntree();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTREE__NOM = eINSTANCE.getEntree_Nom();

    /**
     * The meta object literal for the '<em><b>Valeur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTREE__VALEUR = eINSTANCE.getEntree_Valeur();

    /**
     * The meta object literal for the '{@link fr.n7.algorithme_xtext.impl.SortieImpl <em>Sortie</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.algorithme_xtext.impl.SortieImpl
     * @see fr.n7.algorithme_xtext.impl.Algorithme_xtextPackageImpl#getSortie()
     * @generated
     */
    EClass SORTIE = eINSTANCE.getSortie();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SORTIE__NOM = eINSTANCE.getSortie_Nom();

    /**
     * The meta object literal for the '<em><b>Valeur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SORTIE__VALEUR = eINSTANCE.getSortie_Valeur();

  }

} //Algorithme_xtextPackage
