/**
 * generated by Xtext 2.32.0
 */
package fr.n7.algorithme_xtext;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Algorithme Elements</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.n7.algorithme_xtext.Algorithme_xtextPackage#getAlgorithmeElements()
 * @model
 * @generated
 */
public interface AlgorithmeElements extends EObject
{
} // AlgorithmeElements
