/**
 * generated by Xtext 2.32.0
 */
package fr.n7.algorithme_xtext;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Algorithme</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.algorithme_xtext.Algorithme#getNom <em>Nom</em>}</li>
 *   <li>{@link fr.n7.algorithme_xtext.Algorithme#getAlgorithmeElements <em>Algorithme Elements</em>}</li>
 * </ul>
 *
 * @see fr.n7.algorithme_xtext.Algorithme_xtextPackage#getAlgorithme()
 * @model
 * @generated
 */
public interface Algorithme extends EObject
{
  /**
   * Returns the value of the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nom</em>' attribute.
   * @see #setNom(String)
   * @see fr.n7.algorithme_xtext.Algorithme_xtextPackage#getAlgorithme_Nom()
   * @model
   * @generated
   */
  String getNom();

  /**
   * Sets the value of the '{@link fr.n7.algorithme_xtext.Algorithme#getNom <em>Nom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nom</em>' attribute.
   * @see #getNom()
   * @generated
   */
  void setNom(String value);

  /**
   * Returns the value of the '<em><b>Algorithme Elements</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.algorithme_xtext.AlgorithmeElements}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Algorithme Elements</em>' containment reference list.
   * @see fr.n7.algorithme_xtext.Algorithme_xtextPackage#getAlgorithme_AlgorithmeElements()
   * @model containment="true"
   * @generated
   */
  EList<AlgorithmeElements> getAlgorithmeElements();

} // Algorithme
