/*
 * generated by Xtext 2.32.0
 */
package fr.n7.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.n7.Table_xtextRuntimeModule;
import fr.n7.Table_xtextStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Table_xtextIdeSetup extends Table_xtextStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Table_xtextRuntimeModule(), new Table_xtextIdeModule()));
	}
	
}
