<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="table" nsURI="http://table" nsPrefix="table">
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="tableSansNom"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="colonnes" upperBound="-1"
        eType="#//Colonne" eOpposite="#//Colonne/table"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="idColonne" lowerBound="1"
        eType="#//Colonne"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ColonnesElementsType">
    <eLiterals name="Float"/>
    <eLiterals name="Int" value="1"/>
    <eLiterals name="String" value="2"/>
    <eLiterals name="Bool" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Colonne">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="colonneSansNom" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="#//Table"
        eOpposite="#//Table/colonnes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ElementType" lowerBound="1"
        eType="#//ColonnesElementsType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contraintes" eType="#//Contrainte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbLignes" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contenu" eType="#//Contenu"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColonneProvient" eSuperTypes="#//Colonne">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tableOrigine" lowerBound="1"
        eType="#//Table"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refColonne" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColonneDerivee" eSuperTypes="#//Colonne">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithme" lowerBound="1"
        eType="ecore:EClass ../Algorithme/Algorithme.ecore#//Algorithme"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="colonnesEntree" upperBound="-1"
        eType="#//Colonne"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contenu" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContenuFloat" eSuperTypes="#//Contenu">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contenu" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContenuInt" eSuperTypes="#//Contenu">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contenu" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContenuBool" eSuperTypes="#//Contenu">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contenu" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContenuString" eSuperTypes="#//Contenu">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contenu" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contrainte" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ou" eSuperTypes="#//Contrainte">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" lowerBound="2"
        upperBound="-1" eType="#//Contrainte"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Et" eSuperTypes="#//Contrainte">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" lowerBound="2"
        upperBound="-1" eType="#//Contrainte"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Predicat" abstract="true" eSuperTypes="#//Contrainte">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" lowerBound="1"
        eType="#//Condition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredicatValeur" eSuperTypes="#//Predicat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparant" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredicatColonne" eSuperTypes="#//Predicat">
    <eStructuralFeatures xsi:type="ecore:EReference" name="colonneComparante" lowerBound="1"
        eType="#//Colonne"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Condition">
    <eLiterals name="InferieurOuEgal"/>
    <eLiterals name="InferieurStrict" value="1"/>
    <eLiterals name="Egal" value="2"/>
    <eLiterals name="SuperieurStrict" value="3"/>
    <eLiterals name="SuperieurOuEgal" value="4"/>
  </eClassifiers>
</ecore:EPackage>
