/*
 * generated by Xtext 2.32.0
 */
package fr.n7.ui.tests;

import com.google.inject.Injector;
import fr.n7.table_xtext.ui.internal.Table_xtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class Table_xtextUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Table_xtextActivator.getInstance().getInjector("fr.n7.Table_xtext");
	}

}
